### ISSUE TITLE
Two things 

### ISSUE THREAD

**Issue by DraGiuS** [verkiya/Dev-untu#2]
1 : Can you please upload your sources, i mean, how you created the iso ? Tools ?
2 : Can you update the build, up to Ubuntu 18.04.1 ?

Thanks..

**Comment by verkiya** [comment]
1:@DraGiuS Thank you so much for showing your interest I'll surely make amendments in a short while. :)
Again, Thanks :+1: 
2: No Problem, I'll try to do.

**Comment by DraGiuS** [comment]
What about the second point ?

**Comment by verkiya** [comment]
I'm currently busy with some other things , i'll surely make it done within a week in a new repo. Currently Organizing my GIthub for now.
Thanks :)

**Comment by DraGiuS** [comment]
?
